---
title: "map"
author: "kangminji"
date: '2021 5 13 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R로 인터렉티브 지도 그리기(leaflet)
```{r}
library(leaflet)
```

```{r}
leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles()
```

```{r}
leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addProviderTiles('Stamen.TonerLite')

leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addProviderTiles('CartoDB.Positron')

leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addProviderTiles('Esri.NatGeoWorldMap')
```

기본 Marker 달기
```{r}
leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles() %>% 
  addMarkers(lng=127.386,lat=36.3508, label='대전시청')

leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles() %>% 
  addMarkers(lng=127.386,lat=36.3508, label='대전시청',
             labelOptions=labelOptions(textsize = '15px'))

leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles() %>% 
  addMarkers(lng=127.386,lat=36.3508, label='대전시청',
             labelOptions=labelOptions(style = list('color'= 'red', 'font-size'='15px',
                                                    'font-style'='italic')))
```

circle Marker
```{r}
leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles() %>% 
  addCircles(lng=127.386,lat=36.3508, label='대전시청', radius=500)   #radius=: 반지름 크기

leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles() %>% 
  addCircles(lng=127.386,lat=36.3508, label='대전시청', radius=500,
             weight=1, color='#dd0022')
```

사각형 Marker
```{r}
leaflet() %>% 
  setView(lng=127.39, lat = 36.35, zoom = 12) %>% 
  addTiles() %>% 
  addRectangles(lng1 = 127.37, lat1 = 36.34,
                lng2 = 127.39, lat2 = 36.36,
                fillColor = 'transparent')
```


















