---
title: "Sentiment Analysis"
author: "kangminji"
date: '2021 5 7 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

IMDB 영화평 감성분석

데이터 모델링
```{r}
#install.packages("text2vec")
library(text2vec)
library(caret)
library(tm)

str(movie_review)
#중요한것: sentiment=1: 긍정, review
```
8:2비율로 훈련/테스트 데이터 셋 분할
```{r}
train_list <- createDataPartition(y= movie_review$sentiment, 
                                  p=0.8, list = F)
mtrain <- movie_review[train_list,]
mtest <- movie_review[-train_list,]
```

훈련 데이터셋에 대해 DTM구축
(테스트 데이터셋에 대해서도 동일하게 적용해야 함)
```{r}
doc <- Corpus(VectorSource(mtrain$review))
doc <- tm_map(doc, content_transformer(tolower))
doc <- tm_map(doc, removeNumbers)
stop_words <- c(stopwords('en'),'<br />')
doc <- tm_map(doc, removeWords, stop_words)
doc <- tm_map(doc, removePunctuation)
doc <- tm_map(doc, stripWhitespace)


#DTM을 이용하여 숫자로 변환
dtm <- DocumentTermMatrix(doc, control = list(weighting=weightTf))
dim(dtm)
dtm[1, ]  #168개는 1이상 숫자로 채워져있지만 나머지는 0 
          #1개의 문서만 보여줌
inspect(dtm)

dtm_tfidf <- DocumentTermMatrix(doc, control=list(weighting=weightTfIdf))
inspect(dtm_tfidf)
```

모델링이 가능한 형태로 DTM을 변환
```{r}
dtm_small <- removeSparseTerms(dtm, 0.9)
dim(dtm_small)
```

sentiment(y)와 DTM을 묶어서 데이터프레임 생성
```{r}
X <- as.matrix(dtm_small)
dataTrain <- as.data.frame(cbind(mtrain$sentiment, X))
head(dataTrain)
colnames(dataTrain)[1] <- 'y'
dataTrain$y <- as.factor(dataTrain$y)
```

Decision tree로 학습
```{r}
library(rpart)
dt <- rpart(y~., dataTrain)
```

테스트 데이터셋으로 모델 성능 평가
테스트 집합으로 DTM구축
```{r}
docTest <- Corpus(VectorSource(mtest$review))
docTest <- tm_map(docTest, content_transformer(tolower))
docTest <- tm_map(docTest, removeNumbers)
docTest <- tm_map(docTest, removeWords, stop_words)
docTest <- tm_map(docTest, removePunctuation)
docTest <- tm_map(docTest, stripWhitespace)
```
DTM으로 숫자로 변환
```{r}
dtmTest <- DocumentTermMatrix(docTest,
                        control=list(dictionary=dtm_small$dimnames$Terms))
#dictionary=dtm_small$dimnames$Terms: train에서 훈련했던 것 사용해라
dim(dtmTest)
inspect(dtmTest)
```

sentiment(y)와 DTM을 묶어서 데이터프레임 생성
```{r}
X <- as.matrix(dtmTest)
dataTest <- as.data.frame(cbind(mtest$sentiment, X))
head(dataTest)
colnames(dataTest)[1] <- 'y'
dataTest$y <- as.factor(dataTest$y)
```

학습했던 모델(Decisiontree)로 예측
```{r}
dt_pred <- predict(dt,dataTest, type='class')
table(dt_pred, dataTest$y)  #혼동행렬 생성
#322+376/1000 = 1000개의 문서에서 69.8%의 정확률을 얻음
```

SVM으로 훈련
```{r}
library(e1071)
svc <- svm(y~., dataTrain)
sv_pred <- predict(svc, dataTest, type='class')
table(sv_pred, dataTest$y)  #74%
```

#########################################################################
#########################################################################

Tf-Idf로 변환
```{r}
dtm_tfidf <- DocumentTermMatrix(doc, control=list(weighting=weightTfIdf))
inspect(dtm_tfidf)
```

모델링이 가능한 형태로 DTM을 변환
```{r}
dtm_small_tfidf <- removeSparseTerms(dtm_tfidf, 0.9)
dim(dtm_small_tfidf)
```

sentiment(y)와 DTM을 묶어서 데이터프레임 생성
```{r}
X <- as.matrix(dtm_small_tfidf)
dataTrain <- as.data.frame(cbind(mtrain$sentiment, X))
head(dataTrain)
colnames(dataTrain)[1] <- 'y'
dataTrain$y <- as.factor(dataTrain$y)
```

Decision tree로 학습
```{r}
library(rpart)
dt_tfidf <- rpart(y~., dataTrain)
```
test data set
```{r}
dtmTest_tfidf <- DocumentTermMatrix(docTest,
                  control=list(dictionary=dtm_small_tfidf$dimnames$Terms,
                               weighting=weightTfIdf))
#dictionary=dtm_small$dimnames$Terms: train에서 훈련했던 것 사용해라
dim(dtmTest_tfidf)
inspect(dtmTest_tfidf)

X <- as.matrix(dtmTest_tfidf)
dataTest <- as.data.frame(cbind(mtest$sentiment, X))
head(dataTest)
colnames(dataTest)[1] <- 'y'
dataTest$y <- as.factor(dataTest$y)
```

예측
```{r}
dt_pred_tfidf <- predict(dt_tfidf, dataTest, type = 'class')
table(dt_pred_tfidf, dataTest$y)
```
SVM으로 훈련
```{r}
library(e1071)
svc_tfidf <- svm(y~., dataTrain)
sv_pred_tfidf <- predict(svc_tfidf, dataTest, type='class')
table(sv_pred_tfidf, dataTest$y)  #74%
```





